# Generated by Django 2.1.1 on 2018-10-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_project_visualization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='batsmen',
            new_name='batsman',
        ),
        migrations.RenameField(
            model_name='deliveries',
            old_name='innings',
            new_name='inning',
        ),
        migrations.AlterField(
            model_name='matches',
            name='season',
            field=models.IntegerField(),
        ),
    ]
