# Generated by Django 2.1.1 on 2018-10-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_project_visualization', '0002_auto_20181002_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_project_visualization.Matches'),
        ),
    ]
