# Generated by Django 2.1.1 on 2018-10-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_project_visualization', '0004_auto_20181002_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='leg_bye_runs',
            new_name='legbye_runs',
        ),
    ]
